name: Sushidynamicshop
version: 1.5
main: mcsushi.dynamicshop.sushidynamicshop.Sushidynamicshop
api-version: 1.20
authors: [NogginTime, StanSethley]
depend: [Vault]
softdepend: [MMOItems, MythicLib, PlayerPoints]

commands:
  sushishop:
    description: Open the dynamic sushi shop GUI
    usage: /sushishop
    aliases: [dynamicshop, sshop, ds]
    permission: sushishop.open
permissions:
  sushishop.open:
    description: Allows opening the sushi shop menu
    default: true
  sushishop.open.self:
    description: Allows opening shops for yourself using /sshop open <shopId>
    default: true
  sushishop.open.others:
    description: Allows opening shops for other players using /sshop open <shopId> <player>
    default: op