name: Sushidynamicshop
version: 1.3
main: mcsushi.dynamicshop.sushidynamicshop.Sushidynamicshop
api-version: 1.20
authors: [NogginTime, StanSethley]
depend: [Vault]
softdepend: [MMOItems, MythicLib, PlayerPoints]

commands:
  sushishop:
    description: Open the dynamic sushi shop GUI
    usage: /sushishop
    aliases: [dynamicshop, sshop, ds]
    permission: sushishop.open
permissions:
  sushishop.open:
    description: Allows opening the sushi shop menu
    default: true